# -*- coding: utf-8 -*-
"""VGSales_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeZIILRD0GAGPS9RIMIJG5E7wP6--whG
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns


#Keep line commented out durring editing for easier workflow
from google.colab import files
uploaded = files.upload()

#set up main frame, add drop.isna later after we get problems sorted out properly

ds = 'vgsales(data_fix).csv'
df = pd.read_csv(ds)
df.drop(df.columns[0], axis=1, inplace=True)


#setting up important frames, first 4 are just column + total sales, sales frames are just dropping all other sales
#genre_platform is how to set up frames where data is needed to be structured for multiple variables

publisher_sales = df.groupby('Publisher')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
genre_sales = df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
year_sales = df.groupby('Year')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
na_sales = df.drop(columns=['EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='NA_Sales', ascending=False).reset_index()
eu_sales = df.drop(columns=['NA_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='EU_Sales', ascending=False).reset_index()
jp_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='JP_Sales', ascending=False).reset_index()
other_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales']).sort_values(by='Other_Sales', ascending=False).reset_index()
genre_platform_sales = df.groupby(['Genre', 'Platform'])['Global_Sales'].sum().reset_index()




display(df)

# GROUP QUESTION 1: Correlation between best preforming genere and platform?
# Made by: Sean

# Check Global_Sales for a genre vs number of games for the genre per top 4 platform

# heads of needed frames
headplat = platform_sales.head(4)
headgen = genre_sales.head(4)

# a is a frame being made to set up count, isin cuts anything that is not in that specified grouping, & in the middle makes it
# check multiple varriables
a = df[df['Genre'].isin(headgen['Genre']) & df['Platform'].isin(headplat['Platform'])]

# Set up platform frames
ps3frame = a[a['Platform']=='PS3'].sort_values(by='Genre', ascending=True).reset_index()
ps2frame = a[a['Platform']=='PS2'].sort_values(by='Genre', ascending=True).reset_index()
wiiframe = a[a['Platform']=='Wii'].sort_values(by='Genre', ascending=True).reset_index()
X360frame = a[a['Platform']=='X360'].sort_values(by='Genre', ascending=True).reset_index()

# Using presetablished genre_platform_sales frame, grab total sales for relevant platforms
ps3total = genre_platform_sales[genre_platform_sales['Platform']=='PS3']
ps3total = ps3total[ps3total['Genre'].isin(headgen['Genre'])].sort_values(by='Genre', ascending=True).reset_index()
ps2total = genre_platform_sales[genre_platform_sales['Platform']=='PS2']
ps2total = ps2total[ps2total['Genre'].isin(headgen['Genre'])].sort_values(by='Genre', ascending=True).reset_index()
wiitotal = genre_platform_sales[genre_platform_sales['Platform']=='Wii']
wiitotal = wiitotal[wiitotal['Genre'].isin(headgen['Genre'])].sort_values(by='Genre', ascending=True).reset_index()
X360total = genre_platform_sales[genre_platform_sales['Platform']=='X360']
X360total = X360total[X360total['Genre'].isin(headgen['Genre'])].sort_values(by='Genre', ascending=True).reset_index()

# Plot first half of frames
fig, ax = plt.subplots(2, 2, figsize=(10, 10))

# Strip plot to plot the preformance of every individual game
sns.stripplot(data=ps3frame, x='Genre', y='Global_Sales', ax=ax[0][0], hue='Genre')
# Set y limits to keep data lables consistant across charts
ax[0][0].set_ylim(0, 25)
ax[0][0].set_title('PS3 Sales by Genre')
ax[0][0].set_xlabel('Genre')
ax[0][0].set_ylabel('Global Sales (in Millions)')

# Bar plot to plot total sales per genre
sns.barplot(data=ps3total, x='Genre', y='Global_Sales', ax=ax[0][1], hue='Genre')
ax[0][1].set_ylim(0, 400)
ax[0][1].set_title('PS3 Total Sales by Genre')
ax[0][1].set_xlabel('Genre')
ax[0][1].set_ylabel('Global Sales (in Millions)')


sns.stripplot(data=ps2frame, x='Genre', y='Global_Sales', ax=ax[1][0], hue='Genre')
ax[1][0].set_ylim(0, 25)
ax[1][0].set_title('PS2 Sales by Genre')
ax[1][0].set_xlabel('Genre')
ax[1][0].set_ylabel('Global Sales (in Millions)')

sns.barplot(data=ps2total, x='Genre', y='Global_Sales', ax=ax[1][1], hue='Genre')
ax[1][1].set_ylim(0, 400)
ax[1][1].set_title('PS2 Total Sales by Genre')
ax[1][1].set_xlabel('Genre')
ax[1][1].set_ylabel('Global Sales (in Millions)')

# Q1 PART 2 FOR ADDITIONAL PLOT
# Plot second half of frames

fix, ax = plt.subplots(2, 2, figsize=(10, 10))
sns.stripplot(data=wiiframe, x='Genre', y='Global_Sales', ax=ax[0][0], hue='Genre')
# no limit here because the wii has a massive outlier
ax[0][0].set_title('Wii Sales by Genre')
ax[0][0].set_xlabel('Genre')
ax[0][0].set_ylabel('Global Sales (in Millions)')

sns.barplot(data=wiitotal, x='Genre', y='Global_Sales', ax=ax[0][1], hue='Genre')
ax[0][1].set_ylim(0, 400)
ax[0][1].set_title('Wii Total Sales by Genre')
ax[0][1].set_xlabel('Genre')
ax[0][1].set_ylabel('Global Sales (in Millions)')


sns.stripplot(data=X360frame, x='Genre', y='Global_Sales', ax=ax[1][0], hue='Genre')
ax[1][0].set_ylim(0, 25)
ax[1][0].set_title('X360 Sales by Genre')
ax[1][0].set_xlabel('Genre')
ax[1][0].set_ylabel('Global Sales (in Millions)')
# AI used to correct chart lables from float to int to match other charts
# Start
ax[1][0].yaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%d'))
# End

sns.barplot(data=X360total, x='Genre', y='Global_Sales', ax=ax[1][1], hue='Genre')
ax[1][1].set_ylim(0, 400)
ax[1][1].set_title('X360 Total Sales by Genre')
ax[1][1].set_xlabel('Genre')
ax[1][1].set_ylabel('Global Sales (in Millions)')

#Additional Frame for potential in class questions
# AI utilized to simplify process from complicated form outlined before
# Start
top_outliers = a.loc[a.groupby(['Platform', 'Genre'])['Global_Sales'].idxmax()]

for index, row in top_outliers.iterrows():
    print(f"Platform: {row['Platform']}, Genre: {row['Genre']}, Top Outlier: {row['Name']} (Sales: {row['Global_Sales']:.2f}M)")
# End

#GROUP QUESTION 2: How do top sales differ by region?
# Made by: Charles
#Up to interpretation, just plot some differences between the 3
info = pd.DataFrame({
    'Game Name': df['Name'].head(5),
    'NA_Sales' : df['NA_Sales'].head(5),
    'EU_Sales' : df['EU_Sales'].head(5),
    'JP_Sales' : df['JP_Sales'].head(5)
})

info.plot(x = 'Game Name', y = ["JP_Sales", "NA_Sales", "EU_Sales"], kind="bar")
plt.ylabel("Sales (In Millions)")
plt.show()

#GROUP QUESTION 3: How does the average game sales change year over year?
# Made by: Charles

dataFrame = pd.DataFrame(
  {
    "years" : df['Year'],
    "NA_sales" : df['NA_Sales'],
    "EU_sales" : df['EU_Sales'],
    "JP_sales" : df['JP_Sales'],
    "Other_sales" : df['Other_Sales'],
  }

)
plt.plot(dataFrame.groupby(["years"]).mean())
plt.xlabel('Year Released')
plt.ylabel('Average Game Sales')
plt.legend(["NA Sales","EU Sales" ,"JP Sales", "Other Sales"])
plt.show()

#GROUP QUESTION 4: Does having a large publisher size of released games correlate to having good sales?
# Made by: Jake
#Maybe grab random publishers and compare their games made vs sales?
#Used AI to double check and accurately get publisher stats for sales

publisher_stats_filtered = (df.groupby('Publisher')
      .agg(
          Game_Count=('Name', 'count'),
          Total_Global_Sales=('Global_Sales', 'sum'),
          Avg_Global_Sales=('Global_Sales', 'mean')
          )
      .reset_index()
)
publisher_stats_filtered = publisher_stats_filtered[publisher_stats_filtered['Game_Count'] >= 5]
sorted_publishers = publisher_stats_filtered.sort_values(
    by='Avg_Global_Sales',
    ascending=False
)

# top 3 publishers
top_3 = sorted_publishers.head(3)

# middle 3 publishers
mid_index = len(sorted_publishers) // 2
mid_3 = sorted_publishers.iloc[mid_index-1:mid_index+2]

# bottom 3 publishers
bottom_3 = sorted_publishers.tail(3)
plt.figure(figsize=(10,6))
#Scatter plot would display every publisher with all of their games and sales
plt.scatter(
    publisher_stats_filtered['Game_Count'],
    publisher_stats_filtered['Avg_Global_Sales'],
    color='gray',
    alpha=0.4,
    label='All Publishers'
)
# highlight top 3
plt.scatter(
    top_3['Game_Count'],
    top_3['Avg_Global_Sales'],
    color='green',
    s=100,
    label='Top 3 Publishers'
)
# highlight middle 3
plt.scatter(
    mid_3['Game_Count'],
    mid_3['Avg_Global_Sales'],
    color='blue',
    s=100,
    label='Middle 3 Publishers'
)

# highlight bottom 3
plt.scatter(
    bottom_3['Game_Count'],
    bottom_3['Avg_Global_Sales'],
    color='red',
    s=100,
    label='Bottom 3 Publishers'
)

# label highlighted publishers
for _, row in top_3.iterrows():
    plt.text(row['Game_Count'], row['Avg_Global_Sales'], row['Publisher'])

plt.xlabel('Number of Games Published')
plt.ylabel('Average Global Sales (Millions)')
plt.title('Publisher Size vs Average Global Sales')
plt.grid(True)

plt.show()

# GROUP QUESTION 5: Does platform affect the sales of a game?
# Made by: Sean
# Compare game sales for a few games that are shared across multiple consoles

SameGen=df[df['Platform'].isin(['PS3', 'X360', 'Wii'])]

# AI Used to help create this frame due to confusion on if it would work or not
# Start
name_counts = SameGen['Name'].value_counts()
frequent_names = name_counts[name_counts == 3].index
SameGen = SameGen[SameGen['Name'].isin(frequent_names)].sort_values(by='Name').reset_index(drop=True)
# End


names = []

for i in range(0, 5):
  namcheck = SameGen['Name'][np.random.randint(0, len(SameGen))]
  if namcheck not in names:
    names.append(namcheck)
  else:
    i=i-1


plotnames = SameGen[SameGen['Name'].isin(names)]

pnw = plotnames[plotnames['Platform'].isin(['Wii'])]
pnx = plotnames[plotnames['Platform'].isin(['X360'])]
pns = plotnames[plotnames['Platform'].isin(['PS3'])]

figure, ax = plt.subplots(1, 3, figsize=(15, 10), layout='constrained')

# AI assistance in setting up y axis standardization
# Start
max_sales = max(pnw['Global_Sales'].max(), pnx['Global_Sales'].max(), pns['Global_Sales'].max())
# End

ax[0].bar(pnw['Name'], pnw['Global_Sales'], color='grey')
ax[1].bar(pnx['Name'], pnx['Global_Sales'], color = 'green')
ax[2].bar(pns['Name'], pns['Global_Sales'], color = 'blue')

# AI helping to standardize y axis between charts
# Start
for a in ax:
    a.set_ylim(0, max_sales * 1.1)
# End

ax[0].set_title('Wii Sales')
ax[0].legend(['Sales in Millions'])
ax[1].set_title('X360 Sales')
ax[1].legend(['Sales in Millions'])
ax[2].set_title('PS3 Sales')
ax[2].legend(['Sales in Millions'])

for a in ax:
    a.set_ylabel('Global Sales in Millions')
    a.set_xlabel('Game Name')
    plt.setp(a.get_xticklabels(), rotation=45, ha='right')

plt.suptitle('Global Sales by Game for Different Platforms', fontsize=16)
plt.show()

#Research Question 6(ML): Does Release year predict the number of video games released?
# Made by: Jake
#Sorts data to count the total number of games per year(Used AI to help for counting section)
df_year = (df[['Year', 'Name']]
    .dropna()
    .groupby('Year')['Name']
    .count()
    .reset_index(name='Game_Count')
)
x = df_year['Year']
y = df_year['Game_Count']
#line of regression slope represents the change games being released per year
m, b = np.polyfit(x, y, 1)
plt.figure(figsize=(10,6))
plt.scatter(x, y)
plt.plot(x, m*x + b, linewidth=3)
plt.xlabel('Year')
plt.ylabel('Number of Games Released')
plt.title('Release Year vs Number of Games(Linear Regression)')
plt.xlim(1980, 2015)
plt.grid(True)
plt.show()